### ISSUE TITLE
OSX podspec

### ISSUE THREAD

**Issue by cgmorales** [sdarlington/SDCloudUserDefaults#7]
Hi..
I guess your class works well for OSX too, so you just should add that in the podspec file.
Please, could you do that ? :)
Thanks!

**Comment by sdarlington** [comment]
Can you test it first? I can see that it compiles but I don't have a Mac dev account so I can't test anything with iCloud.

**Comment by sdarlington** [comment]
Release 1.0.2 has OS X support enabled in the podspec. I wasn't able to test it. Please raise new issues (and pull requests!) if you find any problems.
